/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bear.glb --transform 
Files: bear.glb [18.04MB] > /home/mateus/Downloads/lol/bear-transformed.glb [475.23KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bear-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.object_0.geometry} material={materials.object_0} />
      <mesh geometry={nodes.object_1.geometry} material={materials.object_1} />
      <mesh geometry={nodes.object_2.geometry} material={materials.object_2} />
      <mesh geometry={nodes.object_3.geometry} material={materials.object_3} />
    </group>
  )
}

useGLTF.preload('/bear-transformed.glb')
